### ISSUE TITLE
Raspberry Pi mit Android Gerät verbinden

### ISSUE THREAD

**Issue by Oldbaas** [bfh/ABCD#1]
Das Raspberry Pi muss so Programmiert werden damit es ein Android - Smartphone sobald es eingesteckt wird erkennt und ein Datenverbindung hergestellt wird.

Zuerst muss das Android Gerät als USB Drive erkannt werden (So dass der Host (Raspberry Pi) auf das Device (Android Gerät) zugreiffen kann.

**Comment by gradnik** [comment]
Ich habe bis jetzt lediglich eine App gefunden, die das Smartphone als USB Drive erscheinen lässt. Die ist jedoch kostenpflichtig und ich bin mir sicher, dass es eine bessere Möglichkeit gibt das selbe Ziel zu erreichen.

**Comment by gradnik** [comment]
Folgendes könnte funktionieren:
1. Turn on USB debugging by click Menu > Setting > Applications > Development > USB debugging
1. Plug the supplied USB cable into your PC and connect it to your device. A USB icon  will appear in the status bar when the device has been recognized.
2. In the main screen of your Android device, use your finger to pull down the top status bar. Then touch USB Connected.

**Comment by gradnik** [comment]
oder auch:
1: Open the “Setting” > “More…”

2: Search then Tap on “USB utilities”

3: Check the option: “Connect Storage to PC”

**Comment by Oldbaas** [comment]
Die 2 Beispiele die du genannt hast funktionieren bei meinem Samsung Galaxy S6 Edge nicht direkt weil man als erstes noch in den Developer Modus reinkommen muss. Um in den Developer Modus reinzukommen muss man auf dem Gerät in die Einstellungen gehen, Geräteinformationen wählen, Softwareinfo wählen, und Buildnummer ungefähr 7 mal hintereinander drücken dann erscheint der Developermodus und man kann USB Debugging aktivieren.

**Comment by gradnik** [comment]
Super, hat funktioniert
